### ISSUE TITLE
[chore] 프로젝트 기초셋팅

### ISSUE THREAD

**Issue by mdb1217** [TEAM-README/Readme-AOS#1]
## 화면 이름
없음

## 기능 설명
프로젝트 기초셋팅

## 필요 태스크
- [x] 라이브러리 추가
- [x] BindingActivity, Fragment 추가
- [x] 프로젝트 멀티모듈화
- [x] DI 세팅
- [x] 패키징
- [x] 깃허브 액션
- [x] 슬랙-깃허브 연동 
- [x] 이슈, PR 템플릿 적용

**Comment by KxxHyoRim** [comment]
이건 chore가 아니다..😲😲
